#!/bin/bash
source `dirname $0`/libEnv
audisVersion
cleanAndBuild() {
    banner "Doing ${1#make} for AuDis $AUDIS_VERSION and target $toolchain" 3
    set -x
    $1 -c $toolchain $board
    if ! $1 $toolchain $board; then
        $1 -j1 $toolchain $board V=1
    fi
    { set +x; } 2>/dev/null
}
for toolchain in `makeToolchain -h 2>&1 | tail -n1`; do
    board=""
    cleanAndBuild makeToolchain
    AUDIS_TOOL_PATH= cleanAndBuild makeBusybox
    AUDIS_TOOL_PATH= cleanAndBuild makeDropbear
    for board in `makeKernel $toolchain 2>&1 | tail -n1`; do
        AUDIS_TOOL_PATH= cleanAndBuild makeKernel
        AUDIS_TOOL_PATH= cleanAndBuild makeRootfs
    done
done
